config/routes.rb
Rails.application.routes.draw do
  root      "accounts#index"
  resources :transactions
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :deposits, class_name: "Transaction", foreign_key: "to_account_id"
  has_many :withdrawals, class_name: "Transaction", foreign_key: "from_account_id"

  validates :name, presence: true
  def balance
    # deposits
    deposits = self.deposits.sum("amount")
    puts("deposits: #{deposits}")
    # withdrawals
    withdrawals = self.withdrawals.sum("amount")
    puts("withdrawals: #{withdrawals}")
    # balance
    return deposits - withdrawals
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :to_account, class_name: "Account", optional: true
  belongs_to :from_account, class_name: "Account", optional: true

  # validations
  validates :date, presence: true
  validates :amount, presence: true

  validates :to_account_id, presence: {message: "Either to_account_id or from_account_id must be specified"} unless :from_account_id
  validates :from_account_id, presence: {message: "Either to_account_id or from_account_id must be specified"} unless :to_account_id

  validates_associated :to_account
  validates_associated :from_account

 end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all.order(:created_at)
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @transactions = Transaction.where(to_account: params[:id]).or(Transaction.where(from_account: params[:id]))
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def hello
    render html: "main page goes here!"
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all.order(:date)
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    transaction = params[:transaction]

    # set to_/from_account for payment / deposit / transfer
    if transaction[:type] == "deposit"
      # deposit are *to* current account
      transaction[:to_account_id] = params[:account_id]
    else
      # payments and transfers are *from* current account
      transaction[:from_account_id] = params[:account_id]
      if transaction[:transfer]
        transaction[:to_account_id] = transaction[:transfer_account_id]
      end
    end

    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to :controller => 'accounts', :action => 'show', :id => params[:account_id], notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:date, :payee, :note, :amount, :to_account_id, :from_account_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_form.html.slim
= form_with(model: account, local: true) do |form| 
  - if account.errors.any? 
    #error_explanation
      h2 = pluralize(account.errors.count, "error")
        | prohibited this account from being saved:

      ul
      - account.errors.full_messages.each do |message| 
        li = message

  .field
    = form.label :name 
    = form.text_field :name 

  .field
    = form.label :description 
    = form.text_field :description 

  .actions
    = form.submit

app/views/accounts/edit.html.slim
h1 Editing Account

= render 'form', account: @account 

= link_to 'Show', @account
|  |
= link_to 'Back', accounts_path 

app/views/accounts/index.html.slim
p#notice = notice

h1 Accounts

table.table.table-bordered.table-hover
  thead
    tr
      th Name
      th Description
      th Balance

  tbody
    - @accounts.each do |account|
      tr
        td = link_to account.name, account
        td = account.description
        td = number_to_currency(account.balance)
br
= link_to 'New Account', new_account_path

app/views/accounts/new.html.slim
h1 New Account

= render 'form', account: @account

= link_to 'Back', accounts_path

app/views/accounts/show.html.slim
p#notice = notice

p
  strong Name: 
  = @account.name  


p
  strong Description: 
  = @account.description  


= (link_to 'Edit', edit_account_path(@account))
|  |
= (link_to 'Back', accounts_path)

br

h1 Transactions

table.table.table-hover
  thead
    tr
      th: span.glyphicon.glyphicon-remove-sign.remove-button-column
      th Date
      th Payee
      th Note
      th Amount
      th To / From
      th Balance

  tbody
    - balance = 0
    - @transactions.order(:created_at).each do |transaction|
      - is_deposit = transaction.to_account_id == @account.id
      - is_payment = transaction.from_account_id == @account.id
      - is_transfer = transaction.to_account_id && transaction.from_account_id
      - amount = is_payment ? -transaction.amount : transaction.amount
      - balance += amount
      tr
        td = link_to transaction, class: "remove-button", method: :delete, data: {confirm: 'Are you sure?'}
          span.glyphicon.glyphicon-remove-sign
        td = transaction.date
        td = transaction.payee
        td = transaction.note
        td = number_to_currency(amount)
        td = (transaction.to_account_id == @account.id ? transaction.from_account.name : transaction.to_account.name) if is_transfer
        td = number_to_currency(balance)

= link_to 'Add Transaction', new_transaction_path(:account_id => @account.id)

app/views/layouts/_header.html.slim
header
  nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        a.navbar-brand href=(root_path) Bill$!

app/views/layouts/application.html.slim
doctype html
html
  head
    title Bill$
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/header'
    = yield
    = debug(params.inspect) if Rails.env.development?

app/views/transactions/_form.html.slim
= form_with(model: transaction, local: true) do |form| 
  - if transaction.errors.any? 
    #error_explanation
      h2 = pluralize(transaction.errors.count, "error")
        | prohibited this transaction from being saved:
      ul
      - transaction.errors.full_messages.each do |message| 
        li = message

  = hidden_field_tag 'account_id', params[:account_id]

  .form-group
    = form.label :date
    = form.date_select :date

  .form-group
    = form.label :payee
    = form.text_field :payee

  .form-group
    = form.label :note
    = form.text_field :note

  .form-group
    = form.label :type_withdrawal, class: "radio" do
      = form.radio_button :type, 'payment', checked: true
      | Payment

    = form.label :type_deposit, class: "radio" do
      = form.radio_button :type, 'deposit'
      | Deposit

  .form-group
    = form.label :amount
    = form.text_field :amount

  .form-group
    = form.label :transfer
      = form.check_box(:transfer)
      |  Transfer

  .form-group
    = form.label :transfer_account_id
    = form.text_field :transfer_account_id

  .actions
    = form.submit

app/views/transactions/edit.html.slim
h1 Editing Transaction

= render 'form', transaction: @transaction

= link_to 'Show', @transaction
|  |
= link_to 'Back', transactions_path

app/views/transactions/index.html.slim
p#notice = notice

h1 Transactions

table
  thead
    tr
      th Date
      th Payee
      th Note
      th Amount
      th From Account
      th To Account
      th(colspan="3")
    
  tbody
    - @transactions.each do |transaction|
      tr
        td = transaction.date 
        td = transaction.payee 
        td = transaction.note 
        td = number_to_currency(transaction.amount) 
        td = transaction.from_account.name if transaction.from_account 
        td = transaction.to_account.name if transaction.to_account 
        td = link_to 'Show', transaction 
        td = link_to 'Edit', edit_transaction_path(transaction) 
        td = link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } 

= link_to 'New Transaction', new_transaction_path

app/views/transactions/new.html.slim
h1 New Transaction

= render 'form', transaction: @transaction

= link_to 'Back', transactions_path

app/views/transactions/show.html.slim
p#notice = notice

p
  strong Date:
  = @transaction.date 

p
  strong Payee:
  = @transaction.payee 

p
  strong Note:
  = @transaction.note 

p
  strong Amount:
  = @transaction.amount 

p
  strong From Account:
  = @transaction.from_account.name if @transaction.from_account 

p
  strong To Account:
  = @transaction.to_account.name if @transaction.to_account 

= link_to 'Edit', edit_transaction_path(@transaction)
|  |
= link_to 'Back', transactions_path 